### ISSUE TITLE
Use TaskCompletionSource.TrySetCanceled for WaitForRemotePipeCloseAsync

### ISSUE THREAD

**Issue by asyura** [RandomEngy/PipeMethodCalls#9]
i get an error below when closing the program
`An error occurred stopping the application System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource``1.SetCanceled()
   at PipeMethodCalls.PipeMessageProcessor.<WaitForRemotePipeCloseAsync>b__11_0()
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)`

**Comment by RandomEngy** [comment]
Thanks for the report. Should be fixed in 3.0.3.
